name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp-key.json

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash


    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure GCP credentials
      - name: Authenticate with GCP
        run: |
          # Write the JSON content to a file
          echo "${{ secrets.GCP_CREDENTIALS }}" > $GOOGLE_APPLICATION_CREDENTIALS
          ls -l $GOOGLE_APPLICATION_CREDENTIALS
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Check Credentials
        working-directory: .
        run: env | grep GOOGLE_APPLICATION_CREDENTIALS
        
      - name: Terraform Init
        working-directory: .
        run: terraform init -upgrade
      
      - name: Terraform Validate
        working-directory: .
        run: terraform validate

      - name: Terraform Apply
        working-directory: .
        run: terraform apply -target=module.gcp_infrastructure -auto-approve
